# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Eyowo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eyowo
pod 'Alamofire', '~> 5.4'
pod 'SwiftyJSON', '~> 4.0'

end
